baseurl = "/"
languageCode = "en-us"
title = "Centre County DSA"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "Organizing for Socialism in Centre County Pennsylvania"
  cover = "images/cover.jpg"
  author = "Centre County DSA"
  authorlocation = "State College, PA"
  authorwebsite = "https://www.centrecodsa.com"
  bio= "About"
  logo = "images/logo.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "CentreCoDSAOrg"
  twitterName = "centrecodsa"
  facebookName = "centrecodsa"
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
  twitter = "centrecodsa"
