backend:
  name: github
  repo: CentreCountyDSAOrg/website # Path to your Github repository
  branch: master # Branch to update (master by default)

publish_mode: editorial_workflow

media_folder: "site/static/img/blog" # Folder where user uploaded files should go
public_folder: "/img/blog"

collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - name: "event"
    label: "Event"
    folder: "site/content/event"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "When", name: "when", widget: "datetime", tagname: "h2"}
      - {label: "Where", name: "where", widget: "string", tagname: "h2"}
      - {label: "Facebook Event Link", name: "fb_event_link", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
  - name: "announcement"
    label: "Announcement"
    folder: "site/content/announcement"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
